[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remmappings = ["@chainlink/contracts/=lib/chainlink-brownine-contracts/contracts/", ]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
include_paths = ["../"]
